// <auto-generated />
using System;
using Hospital_management_system.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_management_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113100559_InitializeDB")]
    partial class InitializeDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0 AND [code] <> ''");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0 AND [name] <> ''");

                    b.ToTable("tbl_departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = "4aa491b1-97cb-4189-8e03-d4ea8c27af6d",
                            Code = "CAD",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heart and Cardiovascular Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cardiology"
                        },
                        new
                        {
                            DepartmentId = "80655e05-0aa7-4feb-860e-32ac14a19864",
                            Code = "PED",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Children Health Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            DepartmentId = "2883fe52-f4ca-4ce2-9999-6c0280668b2f",
                            Code = "ORTH",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bone and Joint Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            DepartmentId = "4e795955-b97a-4f02-b6bd-334df9f79e47",
                            Code = "GM",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "General Health Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "General Medicine"
                        },
                        new
                        {
                            DepartmentId = "d3200872-4f52-4982-b1a4-0ed85ee3f927",
                            Code = "EMG",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Emergency Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Emergency"
                        },
                        new
                        {
                            DepartmentId = "63347532-a564-4e23-a5d9-c7de4ef82da0",
                            Code = "IT",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Information Technology",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.Property<string>("DoctorId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("license_number");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("specialization");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("staff_id");

                    b.Property<bool>("StoppedWork")
                        .HasColumnType("bit")
                        .HasColumnName("stopped_work");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience ");

                    b.HasKey("DoctorId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0 AND [license_number] <> ''");

                    b.HasIndex("Specialization");

                    b.HasIndex("StaffId")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("tbl_doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = "f23d761d-82be-42e1-8bc8-19392ed61b62",
                            Code = "S001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LicenseNumber = "LIC-CARD-001",
                            Specialization = "Cardiology",
                            StaffId = "991d5722-d08f-4206-b782-80067da7c4b2",
                            StoppedWork = false,
                            YearsOfExperience = 15
                        },
                        new
                        {
                            DoctorId = "7f760449-40eb-4483-8a34-095bc94c4b46",
                            Code = "S003",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LicenseNumber = "LIC-PED-001",
                            Specialization = "Pediatrics",
                            StaffId = "cb842b1f-e86c-46f0-9176-c7cf53f32d1a",
                            StoppedWork = false,
                            YearsOfExperience = 10
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("patient_id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dob");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("firstname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("lastname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Sickness")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("sickness");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PatientId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("DoctorId");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("tbl_patients", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "LTRIM(RTRIM(ISNULL([Code], ''))) <> ''");

                            t.HasCheckConstraint("CHK_NAME_NOT_EMPTY", "LTRIM(RTRIM(FirstName + ' ' + LastName)) <> ''");
                        });

                    b.HasData(
                        new
                        {
                            PatientId = "23da1e1f-96fd-446e-9568-473762b2049d",
                            Address = "303 River St",
                            Code = "P001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1960-03-10 00:00:00",
                            DoctorId = "f23d761d-82be-42e1-8bc8-19392ed61b62",
                            Email = "frank.white@example.com",
                            FirstName = "Frank",
                            Gender = 0,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "White",
                            PhoneNumber = "555-6666",
                            Sickness = "Headache"
                        },
                        new
                        {
                            PatientId = "847ba0b5-b4c8-4666-9063-c047f89ed82b",
                            Address = "404 Lake Rd",
                            Code = "P002",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "2018-07-01 00:00:00",
                            DoctorId = "7f760449-40eb-4483-8a34-095bc94c4b46",
                            Email = "grace.black@example.com",
                            FirstName = "Grace",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Black",
                            PhoneNumber = "555-7777",
                            Sickness = "Fatigue"
                        },
                        new
                        {
                            PatientId = "d2235564-74c6-4879-a5d6-8e464b062cd3",
                            Address = "505 Mountain View",
                            Code = "P003",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1990-12-25 00:00:00",
                            DoctorId = "f23d761d-82be-42e1-8bc8-19392ed61b62",
                            Email = "henry.green@example.com",
                            FirstName = "Henry",
                            Gender = 0,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Green",
                            PhoneNumber = "555-8888",
                            Sickness = "Cold"
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("staff_id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dob");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("firstname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hired_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("lastname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("StaffId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("DepartmentId");

                    b.ToTable("tbl_staffs", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "LTRIM(RTRIM(ISNULL([Code], ''))) <> ''")
                                .HasName("CHK_CODE_NOT_EMPTY1");

                            t.HasCheckConstraint("CHK_NAME_NOT_EMPTY", "LTRIM(RTRIM(FirstName + ' ' + LastName)) <> ''")
                                .HasName("CHK_NAME_NOT_EMPTY1");
                        });

                    b.HasData(
                        new
                        {
                            StaffId = "991d5722-d08f-4206-b782-80067da7c4b2",
                            Address = "123 Main St",
                            Code = "S001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1980-05-15 00:00:00",
                            DepartmentId = "4aa491b1-97cb-4189-8e03-d4ea8c27af6d",
                            Email = "alice.smith@hms.com",
                            FirstName = "Alice",
                            Gender = 1,
                            HiredDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Smith",
                            PhoneNumber = "555-1111",
                            Position = "Doctor",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "2db25790-c22a-4adb-8f3b-8e3a7b94d851",
                            Address = "456 Oak Ave",
                            Code = "S002",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1975-08-20 00:00:00",
                            DepartmentId = "4e795955-b97a-4f02-b6bd-334df9f79e47",
                            Email = "bob.johnson@hms.com",
                            FirstName = "Bob",
                            Gender = 0,
                            HiredDate = new DateTime(2005, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Johnson",
                            PhoneNumber = "555-2222",
                            Position = "Nurse",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "cb842b1f-e86c-46f0-9176-c7cf53f32d1a",
                            Address = "789 Pine Ln",
                            Code = "S003",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1990-01-25 00:00:00",
                            DepartmentId = "80655e05-0aa7-4feb-860e-32ac14a19864",
                            Email = "charlie.brown@hms.com",
                            FirstName = "Charlie",
                            Gender = 0,
                            HiredDate = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Brown",
                            PhoneNumber = "555-3333",
                            Position = "Doctor",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "92c7323b-d3c2-4024-826c-2a6d4f357c1c",
                            Address = "101 Hero Way",
                            Code = "S004",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1982-11-03 00:00:00",
                            DepartmentId = "2883fe52-f4ca-4ce2-9999-6c0280668b2f",
                            Email = "diana.prince@hms.com",
                            FirstName = "Diana",
                            Gender = 1,
                            HiredDate = new DateTime(2012, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Prince",
                            PhoneNumber = "555-4444",
                            Position = "Technician",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "bd1a58da-9479-4f52-802e-90e774249411",
                            Address = "202 Secret Rd",
                            Code = "S005",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1995-02-28 00:00:00",
                            DepartmentId = "d3200872-4f52-4982-b1a4-0ed85ee3f927",
                            Email = "eve.adams@hms.com",
                            FirstName = "Eve",
                            Gender = 1,
                            HiredDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Adams",
                            PhoneNumber = "555-5555",
                            Position = "Receptionist",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "83f71025-693f-4067-9b85-84232d4bdce6",
                            Address = "202 Secret Rd",
                            Code = "S006",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "2004-01-01 00:00:00",
                            DepartmentId = "63347532-a564-4e23-a5d9-c7de4ef82da0",
                            Email = "tola.seyha@hms.com",
                            FirstName = "Seyha",
                            Gender = 0,
                            HiredDate = new DateTime(2022, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Tola",
                            PhoneNumber = "1111-1111",
                            Position = "Administrator",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "f80785eb-4de2-4dd6-9467-f3f0df47a952",
                            Address = "202 Secret Rd",
                            Code = "S007",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "2005-01-01 00:00:00",
                            DepartmentId = "63347532-a564-4e23-a5d9-c7de4ef82da0",
                            Email = "tor.soklumor@hms.com",
                            FirstName = "Soklumor",
                            Gender = 0,
                            HiredDate = new DateTime(2022, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Tor",
                            PhoneNumber = "2222-2222",
                            Position = "IT",
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("user_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("staff_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("StaffId")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("tbl_users", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "LTRIM(RTRIM(ISNULL([Code], ''))) <> ''")
                                .HasName("CHK_CODE_NOT_EMPTY2");

                            t.HasCheckConstraint("CHK_NAME_NOT_EMPTY", "LTRIM(RTRIM(Username)) <> ''")
                                .HasName("CHK_NAME_NOT_EMPTY2");
                        });

                    b.HasData(
                        new
                        {
                            UserId = "b2d43c94-c5d0-4d9c-b05f-d27c25a6aaba",
                            Code = "S006",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Password = "123456",
                            StaffId = "83f71025-693f-4067-9b85-84232d4bdce6",
                            Username = "Seyha"
                        },
                        new
                        {
                            UserId = "00ea1daf-21ce-49c7-a12e-1b3e31b2257c",
                            Code = "S007",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Password = "admin",
                            StaffId = "f80785eb-4de2-4dd6-9467-f3f0df47a952",
                            Username = "Lumor"
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Staff", "Staff")
                        .WithOne("Doctor")
                        .HasForeignKey("Hospital_management_system.Domain.Entities.Doctor", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Patient", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.User", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Staff", "Staff")
                        .WithOne("User")
                        .HasForeignKey("Hospital_management_system.Domain.Entities.User", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Department", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
