// <auto-generated />
using System;
using Hospital_management_system.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_management_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112022520_InitializeDB")]
    partial class InitializeDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0 AND [name] <> ''");

                    b.ToTable("tbl_departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = "e50fa8ab-8e3e-476e-8334-bc7ac06ac455",
                            Code = "CAD",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heart and Cardiovascular Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cardiology"
                        },
                        new
                        {
                            DepartmentId = "d8f9eda7-f2b8-4a62-82b6-977a85f09019",
                            Code = "PED",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Children Health Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            DepartmentId = "7cfd457a-d85d-4f92-af68-3faeae8e082e",
                            Code = "ORTH",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bone and Joint Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            DepartmentId = "6c0911bd-028f-428b-8bbd-c9022a4fd283",
                            Code = "GM",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "General Health Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "General Medicine"
                        },
                        new
                        {
                            DepartmentId = "f9e3baff-3824-4922-9eb3-eefa17db75d4",
                            Code = "EMG",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Emergency Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Emergency"
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.Property<string>("DoctorId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("license_number");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("specialization");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("staff_id");

                    b.Property<bool>("StoppedWork")
                        .HasColumnType("bit")
                        .HasColumnName("stopped_work");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience ");

                    b.HasKey("DoctorId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("Specialization");

                    b.HasIndex("StaffId")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("tbl_doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = "f8aea8bd-f4a2-4369-a175-8edc7fe90529",
                            Code = "S001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LicenseNumber = "LIC-CARD-001",
                            Specialization = "Cardiology",
                            StaffId = "ac25e473-b4be-4036-ae2e-c263f160441a",
                            StoppedWork = false,
                            YearsOfExperience = 15
                        },
                        new
                        {
                            DoctorId = "06a79d68-4312-4982-b891-3fcccef4cd8c",
                            Code = "S003",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LicenseNumber = "LIC-PED-001",
                            Specialization = "Pediatrics",
                            StaffId = "5c826fc3-0269-4032-88d7-098f3b860f0d",
                            StoppedWork = false,
                            YearsOfExperience = 10
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("patient_id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dob");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("firstname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("lastname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Sickness")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("sickness");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PatientId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("DoctorId");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("tbl_patients", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "LTRIM(RTRIM(ISNULL([Code], ''))) <> ''");

                            t.HasCheckConstraint("CHK_NAME_NOT_EMPTY", "LTRIM(RTRIM(FirstName + ' ' + LastName)) <> ''");
                        });

                    b.HasData(
                        new
                        {
                            PatientId = "b81b3575-1b36-4480-9a19-485307294920",
                            Address = "303 River St",
                            Code = "P001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1960-03-10 00:00:00",
                            DoctorId = "f8aea8bd-f4a2-4369-a175-8edc7fe90529",
                            Email = "frank.white@example.com",
                            FirstName = "Frank",
                            Gender = 0,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "White",
                            PhoneNumber = "555-6666",
                            Sickness = "Headache"
                        },
                        new
                        {
                            PatientId = "c86e112f-c75e-4a16-b188-bdb652e7602e",
                            Address = "404 Lake Rd",
                            Code = "P002",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "2018-07-01 00:00:00",
                            DoctorId = "06a79d68-4312-4982-b891-3fcccef4cd8c",
                            Email = "grace.black@example.com",
                            FirstName = "Grace",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Black",
                            PhoneNumber = "555-7777",
                            Sickness = "Fatigue"
                        },
                        new
                        {
                            PatientId = "d9c0c301-356c-4439-b0a0-973d9f9be26f",
                            Address = "505 Mountain View",
                            Code = "P003",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1990-12-25 00:00:00",
                            DoctorId = "f8aea8bd-f4a2-4369-a175-8edc7fe90529",
                            Email = "henry.green@example.com",
                            FirstName = "Henry",
                            Gender = 0,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Green",
                            PhoneNumber = "555-8888",
                            Sickness = "Cold"
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("staff_id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dob");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("firstname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hired_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("lastname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("StaffId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("DepartmentId");

                    b.ToTable("tbl_staffs", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "LTRIM(RTRIM(ISNULL([Code], ''))) <> ''")
                                .HasName("CHK_CODE_NOT_EMPTY1");

                            t.HasCheckConstraint("CHK_NAME_NOT_EMPTY", "LTRIM(RTRIM(FirstName + ' ' + LastName)) <> ''")
                                .HasName("CHK_NAME_NOT_EMPTY1");
                        });

                    b.HasData(
                        new
                        {
                            StaffId = "ac25e473-b4be-4036-ae2e-c263f160441a",
                            Address = "123 Main St",
                            Code = "S001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1980-05-15 00:00:00",
                            DepartmentId = "e50fa8ab-8e3e-476e-8334-bc7ac06ac455",
                            Email = "alice.smith@hms.com",
                            FirstName = "Alice",
                            Gender = 1,
                            HiredDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Smith",
                            PhoneNumber = "555-1111",
                            Position = "Doctor",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "6611603a-26b3-45bb-8da0-5b0ca76eb065",
                            Address = "456 Oak Ave",
                            Code = "S002",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1975-08-20 00:00:00",
                            DepartmentId = "6c0911bd-028f-428b-8bbd-c9022a4fd283",
                            Email = "bob.johnson@hms.com",
                            FirstName = "Bob",
                            Gender = 0,
                            HiredDate = new DateTime(2005, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Johnson",
                            PhoneNumber = "555-2222",
                            Position = "Administrator",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "5c826fc3-0269-4032-88d7-098f3b860f0d",
                            Address = "789 Pine Ln",
                            Code = "S003",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1990-01-25 00:00:00",
                            DepartmentId = "d8f9eda7-f2b8-4a62-82b6-977a85f09019",
                            Email = "charlie.brown@hms.com",
                            FirstName = "Charlie",
                            Gender = 0,
                            HiredDate = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Brown",
                            PhoneNumber = "555-3333",
                            Position = "Doctor",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "9f6055bf-c990-43cc-901d-2e669b03ee65",
                            Address = "101 Hero Way",
                            Code = "S004",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1982-11-03 00:00:00",
                            DepartmentId = "7cfd457a-d85d-4f92-af68-3faeae8e082e",
                            Email = "diana.prince@hms.com",
                            FirstName = "Diana",
                            Gender = 1,
                            HiredDate = new DateTime(2012, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Prince",
                            PhoneNumber = "555-4444",
                            Position = "Technician",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "eea784b8-f664-47c7-b328-3beb23eefac7",
                            Address = "202 Secret Rd",
                            Code = "S005",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1995-02-28 00:00:00",
                            DepartmentId = "f9e3baff-3824-4922-9eb3-eefa17db75d4",
                            Email = "eve.adams@hms.com",
                            FirstName = "Eve",
                            Gender = 1,
                            HiredDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Adams",
                            PhoneNumber = "555-5555",
                            Position = "Receptionist",
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Staff", "Staff")
                        .WithOne("Doctor")
                        .HasForeignKey("Hospital_management_system.Domain.Entities.Doctor", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Patient", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Department", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
