// <auto-generated />
using System;
using Hospital_management_system.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_management_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113053847_UserEntityAndLogin")]
    partial class UserEntityAndLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0 AND [code] <> ''");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0 AND [name] <> ''");

                    b.ToTable("tbl_departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = "1642e3af-542f-46f0-9bcc-c1f1b7550386",
                            Code = "CAD",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heart and Cardiovascular Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cardiology"
                        },
                        new
                        {
                            DepartmentId = "dedf8e44-dce2-482b-8b88-ec68b384a14e",
                            Code = "PED",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Children Health Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            DepartmentId = "1077b6fa-06fa-4974-b36e-a75638ba6ea4",
                            Code = "ORTH",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bone and Joint Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            DepartmentId = "91c6b605-97c1-4657-971c-e2e47c02a517",
                            Code = "GM",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "General Health Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "General Medicine"
                        },
                        new
                        {
                            DepartmentId = "2a5d58b7-8fb8-4ad0-aa8c-6ad25d8d8cbb",
                            Code = "EMG",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Emergency Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Emergency"
                        },
                        new
                        {
                            DepartmentId = "38caf774-3b85-4d0d-8a08-ba7e14b8687e",
                            Code = "IT",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Information Technology",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.Property<string>("DoctorId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("license_number");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("specialization");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("staff_id");

                    b.Property<bool>("StoppedWork")
                        .HasColumnType("bit")
                        .HasColumnName("stopped_work");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience ");

                    b.HasKey("DoctorId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0 AND [license_number] <> ''");

                    b.HasIndex("Specialization");

                    b.HasIndex("StaffId")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("tbl_doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = "a9b3dcc7-09bd-43a0-ab07-9d88b8337cda",
                            Code = "S001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LicenseNumber = "LIC-CARD-001",
                            Specialization = "Cardiology",
                            StaffId = "648c2a64-16fc-400e-a974-f14b8e6a44fd",
                            StoppedWork = false,
                            YearsOfExperience = 15
                        },
                        new
                        {
                            DoctorId = "ca00c556-1ac1-4a2f-a894-2b1e766a090a",
                            Code = "S003",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LicenseNumber = "LIC-PED-001",
                            Specialization = "Pediatrics",
                            StaffId = "cabb4ffb-aeaa-453e-9742-12bb0a00c693",
                            StoppedWork = false,
                            YearsOfExperience = 10
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("patient_id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dob");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("firstname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("lastname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Sickness")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("sickness");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PatientId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("DoctorId");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("tbl_patients", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "LTRIM(RTRIM(ISNULL([Code], ''))) <> ''");

                            t.HasCheckConstraint("CHK_NAME_NOT_EMPTY", "LTRIM(RTRIM(FirstName + ' ' + LastName)) <> ''");
                        });

                    b.HasData(
                        new
                        {
                            PatientId = "11e49000-bd3f-4e65-ac10-a7efc086f591",
                            Address = "303 River St",
                            Code = "P001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1960-03-10 00:00:00",
                            DoctorId = "a9b3dcc7-09bd-43a0-ab07-9d88b8337cda",
                            Email = "frank.white@example.com",
                            FirstName = "Frank",
                            Gender = 0,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "White",
                            PhoneNumber = "555-6666",
                            Sickness = "Headache"
                        },
                        new
                        {
                            PatientId = "bc824852-428b-4f0a-a398-f27cd259dbcf",
                            Address = "404 Lake Rd",
                            Code = "P002",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "2018-07-01 00:00:00",
                            DoctorId = "ca00c556-1ac1-4a2f-a894-2b1e766a090a",
                            Email = "grace.black@example.com",
                            FirstName = "Grace",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Black",
                            PhoneNumber = "555-7777",
                            Sickness = "Fatigue"
                        },
                        new
                        {
                            PatientId = "36e3ed7d-9235-4d1c-be78-6bf39f7c5972",
                            Address = "505 Mountain View",
                            Code = "P003",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1990-12-25 00:00:00",
                            DoctorId = "a9b3dcc7-09bd-43a0-ab07-9d88b8337cda",
                            Email = "henry.green@example.com",
                            FirstName = "Henry",
                            Gender = 0,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Green",
                            PhoneNumber = "555-8888",
                            Sickness = "Cold"
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("staff_id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dob");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("firstname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hired_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("lastname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("StaffId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("DepartmentId");

                    b.ToTable("tbl_staffs", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "LTRIM(RTRIM(ISNULL([Code], ''))) <> ''")
                                .HasName("CHK_CODE_NOT_EMPTY1");

                            t.HasCheckConstraint("CHK_NAME_NOT_EMPTY", "LTRIM(RTRIM(FirstName + ' ' + LastName)) <> ''")
                                .HasName("CHK_NAME_NOT_EMPTY1");
                        });

                    b.HasData(
                        new
                        {
                            StaffId = "648c2a64-16fc-400e-a974-f14b8e6a44fd",
                            Address = "123 Main St",
                            Code = "S001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1980-05-15 00:00:00",
                            DepartmentId = "1642e3af-542f-46f0-9bcc-c1f1b7550386",
                            Email = "alice.smith@hms.com",
                            FirstName = "Alice",
                            Gender = 1,
                            HiredDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Smith",
                            PhoneNumber = "555-1111",
                            Position = "Doctor",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "6fdf662c-750e-4e01-af44-5524151e6022",
                            Address = "456 Oak Ave",
                            Code = "S002",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1975-08-20 00:00:00",
                            DepartmentId = "91c6b605-97c1-4657-971c-e2e47c02a517",
                            Email = "bob.johnson@hms.com",
                            FirstName = "Bob",
                            Gender = 0,
                            HiredDate = new DateTime(2005, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Johnson",
                            PhoneNumber = "555-2222",
                            Position = "Nurse",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "cabb4ffb-aeaa-453e-9742-12bb0a00c693",
                            Address = "789 Pine Ln",
                            Code = "S003",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1990-01-25 00:00:00",
                            DepartmentId = "dedf8e44-dce2-482b-8b88-ec68b384a14e",
                            Email = "charlie.brown@hms.com",
                            FirstName = "Charlie",
                            Gender = 0,
                            HiredDate = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Brown",
                            PhoneNumber = "555-3333",
                            Position = "Doctor",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "89454f47-a9c4-43a5-a28e-93f85e8ec5b4",
                            Address = "101 Hero Way",
                            Code = "S004",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1982-11-03 00:00:00",
                            DepartmentId = "1077b6fa-06fa-4974-b36e-a75638ba6ea4",
                            Email = "diana.prince@hms.com",
                            FirstName = "Diana",
                            Gender = 1,
                            HiredDate = new DateTime(2012, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Prince",
                            PhoneNumber = "555-4444",
                            Position = "Technician",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "5a4748d9-6152-4844-9ba5-0001758e9032",
                            Address = "202 Secret Rd",
                            Code = "S005",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "1995-02-28 00:00:00",
                            DepartmentId = "2a5d58b7-8fb8-4ad0-aa8c-6ad25d8d8cbb",
                            Email = "eve.adams@hms.com",
                            FirstName = "Eve",
                            Gender = 1,
                            HiredDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Adams",
                            PhoneNumber = "555-5555",
                            Position = "Receptionist",
                            Salary = 0m
                        },
                        new
                        {
                            StaffId = "369984ef-0787-42d1-b35a-0e863eca3e8e",
                            Address = "202 Secret Rd",
                            Code = "S006",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = "2004-01-01 00:00:00",
                            DepartmentId = "38caf774-3b85-4d0d-8a08-ba7e14b8687e",
                            Email = "tola.seyha@hms.com",
                            FirstName = "Seyha",
                            Gender = 0,
                            HiredDate = new DateTime(2022, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Tola",
                            PhoneNumber = "1111-1111",
                            Position = "Administrator",
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("user_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("staff_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("StaffId")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("tbl_users", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "LTRIM(RTRIM(ISNULL([Code], ''))) <> ''")
                                .HasName("CHK_CODE_NOT_EMPTY2");

                            t.HasCheckConstraint("CHK_NAME_NOT_EMPTY", "LTRIM(RTRIM(Username)) <> ''")
                                .HasName("CHK_NAME_NOT_EMPTY2");
                        });

                    b.HasData(
                        new
                        {
                            UserId = "375dba64-2bfb-4ef8-bf42-de39e9060936",
                            Code = "U001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Password = "123456",
                            StaffId = "369984ef-0787-42d1-b35a-0e863eca3e8e",
                            Username = "Seyha"
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Staff", "Staff")
                        .WithOne("Doctor")
                        .HasForeignKey("Hospital_management_system.Domain.Entities.Doctor", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Patient", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.User", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Staff", "Staff")
                        .WithOne("User")
                        .HasForeignKey("Hospital_management_system.Domain.Entities.User", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Department", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
