// <auto-generated />
using System;
using Hospital_management_system.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_management_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251105173705_AddDepartment")]
    partial class AddDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Appointment", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("appointment_date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("doctor_id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("patient_id");

                    b.Property<string>("Purpose")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("purpose");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AppointmentDate");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("tbl_appointments");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("name <> ''");

                    b.ToTable("tbl_departments");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.Property<string>("DoctorId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hired_date");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("license_number");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("specialization");

                    b.Property<bool>("StoppedWork")
                        .HasColumnType("bit")
                        .HasColumnName("stopped_work");

                    b.Property<int>("YearsOfExperiense")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience ");

                    b.HasKey("DoctorId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("Specialization");

                    b.ToTable("tbl_doctors");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("patient_id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Allergies")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("allergies");

                    b.Property<string>("BloodType")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("blood_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("firstname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("lastname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phonenumber");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PatientId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("tbl_patients", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "LTRIM(RTRIM(ISNULL([Code], ''))) <> ''");

                            t.HasCheckConstraint("CHK_NAME_NOT_EMPTY", "LTRIM(RTRIM(FirstName + ' ' + LastName)) <> ''");
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("staff_id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dob");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("firstname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gender");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hired_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("lastname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("StaffId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("tbl_staffs", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "LTRIM(RTRIM(ISNULL([Code], ''))) <> ''")
                                .HasName("CHK_CODE_NOT_EMPTY1");

                            t.HasCheckConstraint("CHK_NAME_NOT_EMPTY", "LTRIM(RTRIM(FirstName + ' ' + LastName)) <> ''")
                                .HasName("CHK_NAME_NOT_EMPTY1");
                        });
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_management_system.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Staff", "Staff")
                        .WithOne("Doctor")
                        .HasForeignKey("Hospital_management_system.Domain.Entities.Doctor", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.HasOne("Hospital_management_system.Domain.Entities.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Department", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Hospital_management_system.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
