// <auto-generated />
using System;
using Hospital_mangement_system.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_mangement_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_mangement_system.Domain.Entities.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("name <> ''");

                    b.ToTable("tbl_departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = "52188e26-8ca7-485c-a2f5-1766bbc6312f",
                            CreatedAt = new DateTime(2025, 11, 2, 9, 58, 11, 174, DateTimeKind.Utc).AddTicks(2773),
                            Description = "Heart and Cardiovascular Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cardiology"
                        },
                        new
                        {
                            DepartmentId = "0899936b-6a60-41e3-8eb5-6710b63e1b52",
                            CreatedAt = new DateTime(2025, 11, 2, 9, 58, 11, 174, DateTimeKind.Utc).AddTicks(2822),
                            Description = "Children Health Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            DepartmentId = "152b9982-74bf-4c1e-8508-a8c1f3a6183c",
                            CreatedAt = new DateTime(2025, 11, 2, 9, 58, 11, 174, DateTimeKind.Utc).AddTicks(2825),
                            Description = "Bone and Joint Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            DepartmentId = "eb9f87c6-34a2-4b2a-918e-00ff15b8266a",
                            CreatedAt = new DateTime(2025, 11, 2, 9, 58, 11, 174, DateTimeKind.Utc).AddTicks(2828),
                            Description = "General Health Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "General Medicine"
                        },
                        new
                        {
                            DepartmentId = "0ddfad7b-8244-4c41-9163-f878e1a2f4e4",
                            CreatedAt = new DateTime(2025, 11, 2, 9, 58, 11, 174, DateTimeKind.Utc).AddTicks(2831),
                            Description = "Emergency Department",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Emergency"
                        });
                });

            modelBuilder.Entity("Hospital_mangement_system.Domain.Entities.Doctor", b =>
                {
                    b.Property<string>("DoctorId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fullname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gender");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hired_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("license_number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("phonenumber");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("specialization");

                    b.Property<bool>("StoppedWork")
                        .HasColumnType("bit")
                        .HasColumnName("stopped_work");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("YearsOfExperiense")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experiense ");

                    b.HasKey("DoctorId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Fullname")
                        .IsUnique()
                        .HasFilter("fullname <> ''");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("Specialization");

                    b.ToTable("tbl_doctors", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "Code <> ''");
                        });
                });

            modelBuilder.Entity("Hospital_mangement_system.Domain.Entities.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("staff_id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fullname")
                        .UseCollation("SQL_Latin1_General_CP850_BIN");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gender");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hired_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("StaffId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Fullname")
                        .IsUnique()
                        .HasFilter("fullname <> ''");

                    b.ToTable("tbl_staffs", t =>
                        {
                            t.HasCheckConstraint("CHK_CODE_NOT_EMPTY", "Code <> ''")
                                .HasName("CHK_CODE_NOT_EMPTY1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
